image := "kali"
container := "kali-1"

build:
	docker build -t {{image}} .

run:
	docker run --rm --privileged -it --name {{container}} {{image}} /bin/bash || true

cp file dst="/":
	docker cp {{file}} {{container}}:{{dst}}
